#!/usr/bin/env bun
// Copyright 2026 Qianmo AgentNest Team
// SPDX-License-Identifier: AGPL-3.0-or-later

/**
 * Build the `qm` executable: qm and the oh-my-pi CLI compiled into one binary,
 * `dist/qm-<platform>-<arch>`, plus the demo helper bundles in `dist/demo/`
 * (base-switch-omp.md §4.4).
 *
 * Fleet payloads carry no `node_modules`, so everything the node needs at run
 * time is inside the binary: qm's command graph, omp's CLI, and the omp native
 * addon (embedded the way omp's own `build-binary.ts` does it). The compile
 * step is omp's `compileCodingAgent`; only the entry differs — here it is
 * `atlas/packages/node/src/bin/compiled.ts`, which routes `qm agent …` and omp's
 * worker re-entries into the omp CLI and everything else into qm.
 *
 * Usage:
 *   bun atlas/scripts/build-qm.ts                     host target
 *   CROSS_TARGET=linux-x64 bun atlas/scripts/build-qm.ts
 *   BUN_COMPILE_EXECUTABLE_PATH=<bun>                 runtime template override
 *
 * Cross builds need the target's native addon in `packages/natives/native/`
 * (omp's release job fetches them); the host build needs `bun run build:native`.
 *
 * Provenance: before compiling, `src/generated/provenance.ts` (gitignored) is
 * written with `SOURCE_COMMIT` (`<sha>` or `<sha>-dirty`) and `BUILD_TIME`, and
 * removed again afterwards so a source run never reports a stale commit.
 */

import { spawnSync } from 'node:child_process'
import { createRequire } from 'node:module'
import { mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { writeDemoBundles } from './demoBundles.ts'
// The omp build helpers are scripts, not package exports; the path is pinned by
// the base snapshot and the cross-target table below is omp's own.
import { resolveCrossBuild } from '../../packages/coding-agent/scripts/build-binary.ts'
import { compileCodingAgent } from '../../packages/coding-agent/scripts/compile-binary.ts'

const REPO_ROOT = join(import.meta.dir, '..', '..')
const ENTRY = join(
  REPO_ROOT,
  'atlas',
  'packages',
  'node',
  'src',
  'bin',
  'compiled.ts',
)
const PROVENANCE_FILE = join(
  REPO_ROOT,
  'atlas',
  'packages',
  'node',
  'src',
  'generated',
  'provenance.ts',
)
const SHA = /^[0-9a-f]{40}$/

function git(...args: string[]): string {
  const run = spawnSync('git', args, {
    cwd: REPO_ROOT,
    encoding: 'utf8',
    stdio: ['ignore', 'pipe', 'ignore'],
  })
  return run.status === 0 ? run.stdout.trim() : ''
}

/** The commit being built: `QIANMO_SOURCE_COMMIT`, else `HEAD` plus `-dirty` when tracked files differ. */
export function buildSourceCommit(): string {
  const fromEnv = process.env.QIANMO_SOURCE_COMMIT
  if (fromEnv) return fromEnv
  const head = git('rev-parse', 'HEAD')
  if (!SHA.test(head)) return 'unknown'
  return git('status', '--porcelain', '--untracked-files=no') === ''
    ? head
    : `${head}-dirty`
}

function run(command: string[], cwd: string): void {
  const result = Bun.spawnSync(command, {
    cwd,
    stdout: 'inherit',
    stderr: 'inherit',
  })
  if (result.exitCode !== 0) {
    throw new Error(`command failed (${result.exitCode}): ${command.join(' ')}`)
  }
}

function installedVersion(spec: string): string {
  const manifest: unknown = createRequire(import.meta.url)(spec)
  if (
    typeof manifest !== 'object' ||
    manifest === null ||
    !('version' in manifest) ||
    typeof manifest.version !== 'string'
  ) {
    throw new Error(`${spec} has no string version`)
  }
  return manifest.version
}

async function residentExtensionSource(): Promise<string> {
  const result = await Bun.build({
    entrypoints: [join(REPO_ROOT, 'atlas/packages/extension/src/index.ts')],
    target: 'bun',
    format: 'esm',
    packages: 'bundle',
    splitting: false,
  })
  if (!result.success || result.outputs.length !== 1)
    throw new Error('Could not bundle the required resident extension')
  return await result.outputs[0]!.text()
}

async function main(): Promise<void> {
  const cross = resolveCrossBuild(Bun.env.CROSS_TARGET)
  const platform = cross?.platform ?? process.platform
  const arch = cross?.arch ?? process.arch
  const outfile = join(REPO_ROOT, 'dist', `qm-${platform}-${arch}`)
  const adhocSign =
    process.platform === 'darwin' &&
    platform === 'darwin' &&
    Bun.env.BUN_NO_CODESIGN_MACHO_BINARY !== '1'
  const packageDir = join(REPO_ROOT, 'packages', 'coding-agent')

  mkdirSync(join(REPO_ROOT, 'dist'), { recursive: true })
  mkdirSync(join(PROVENANCE_FILE, '..'), { recursive: true })
  writeFileSync(
    PROVENANCE_FILE,
    `// Generated by atlas/scripts/build-qm.ts; not tracked.\nexport const SOURCE_COMMIT = ${JSON.stringify(buildSourceCommit())}\nexport const BUILD_TIME = ${JSON.stringify(new Date().toISOString())}\nexport const RESIDENT_EXTENSION_SOURCE = ${JSON.stringify(await residentExtensionSource())}\n`,
  )
  try {
    // Same pre-steps as omp's build-binary.ts: the stats client archive and the
    // share-viewer tool views are generated, then reset to their placeholders.
    try {
      run(['bun', '--cwd=../stats', 'run', 'gen:stats'], packageDir)
      run(['bun', '--cwd=../collab-web', 'run', 'gen:tool-views'], packageDir)
      await compileCodingAgent({
        repoRoot: REPO_ROOT,
        entrypoint: ENTRY,
        outfile,
        transformersVersion: installedVersion(
          '@huggingface/transformers/package.json',
        ),
        // Portable x64 fleet builds do not need both ~190 MB addon variants.
        // The existing loader already falls back to baseline on modern CPUs.
        native: { platform, arch, x64BaselineOnly: arch === 'x64' },
        target: cross?.target,
        executablePath: Bun.env.BUN_COMPILE_EXECUTABLE_PATH || undefined,
        skipBuiltinCodesign: adhocSign,
      })
    } finally {
      run(['bun', '--cwd=../stats', 'run', 'gen:stats:reset'], packageDir)
    }
    if (adhocSign) {
      run(
        [
          'codesign',
          '--force',
          '--sign',
          '-',
          '--entitlements',
          join(REPO_ROOT, 'scripts', 'macos-entitlements.plist'),
          outfile,
        ],
        REPO_ROOT,
      )
    }
  } finally {
    rmSync(PROVENANCE_FILE, { force: true })
  }
  console.log(`[build-qm] ${outfile}`)

  const bundles = await writeDemoBundles(join(REPO_ROOT, 'dist'))
  console.log(`[build-qm] dist/demo: ${bundles} bundles`)
}

if (import.meta.main) await main()
