#!/usr/bin/env bun
// Copyright 2026 Qianmo AgentNest Team
// SPDX-License-Identifier: AGPL-3.0-or-later

/**
 * Generate the `docs-dev-v1` memory corpus (`docs/dev/memory-m1.md` §2.4
 * item 7) from the repository's own decision records at one pinned commit.
 *
 * Deterministic: it reads the files with `git show <commit>:<path>`, never the
 * working tree, so the output depends on the commit and this code only. The
 * result goes to `packages/recall/eval/corpus/docs-dev.generated.ts`.
 *
 * Personal details are redacted in the whole source file before extraction,
 * and the output is scanned again; it refuses to write when anything
 * survives, or when two records share a key.
 *
 * Usage:
 *   bun run scripts/qianmo-recall-docs-corpus.ts          # (re)generate
 *   bun run scripts/qianmo-recall-docs-corpus.ts --check  # byte-compare only
 *
 * `--check` exits 1 when the committed file differs from a fresh generation,
 * and 2 when the pinned commit is not in this clone (a shallow clone).
 */

import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  type DocsRecord,
  extractRecords,
  personalFindings,
  redactPersonal,
} from '../packages/recall/eval/docs-extract.js'
import {
  DOCS_SOURCE_COMMIT,
  DOCS_SOURCES,
} from '../packages/recall/eval/docs-sources.js'

const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
export const OUTPUT = join(
  REPO_ROOT,
  'packages/recall/eval/corpus/docs-dev.generated.ts',
)

function gitShow(path: string): string | null {
  const result = Bun.spawnSync(
    ['git', 'show', `${DOCS_SOURCE_COMMIT}:${path}`],
    { cwd: REPO_ROOT, stdout: 'pipe', stderr: 'pipe' },
  )
  return result.exitCode === 0 ? result.stdout.toString() : null
}

/** Escape text for a template literal: backslash, backtick, `${`. */
function templateSafe(text: string): string {
  return text
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${')
}

/** The generated module's full text, or `null` when the commit is absent. */
export function generate(): string | null {
  const records: DocsRecord[] = []
  for (const source of DOCS_SOURCES) {
    const markdown = gitShow(source.file)
    if (markdown === null) return null
    // Redact the whole file before anything is cut: a truncation that fell
    // inside a name would leave a fragment the scan below cannot recognise.
    records.push(...extractRecords(redactPersonal(markdown), source))
  }
  const keys = new Set<string>()
  for (const record of records) {
    if (keys.has(record.key)) throw new Error(`duplicate key ${record.key}`)
    keys.add(record.key)
  }
  const json = JSON.stringify(records, null, 2)
  const findings = personalFindings(json)
  if (findings.length > 0) {
    throw new Error(
      `personal detail survived redaction: ${findings.join(', ')}`,
    )
  }
  const digest = createHash('sha256').update(json).digest('hex')
  return [
    '// Copyright 2026 Qianmo AgentNest Team',
    '// SPDX-License-Identifier: AGPL-3.0-or-later',
    '',
    '// GENERATED by scripts/qianmo-recall-docs-corpus.ts from docs/dev at the',
    '// commit below. Do not edit; regenerate, and verify with `--check`.',
    '',
    `export const DOCS_DEV_SOURCE_COMMIT = '${DOCS_SOURCE_COMMIT}'`,
    '',
    `export const DOCS_DEV_RECORD_COUNT = ${records.length}`,
    '',
    '/** SHA-256 of `DOCS_DEV_RECORDS_JSON`, checked when the corpus loads. */',
    // Split the way the formatter would, so `biome ci` accepts the output.
    'export const DOCS_DEV_RECORDS_SHA256 =',
    `  '${digest}'`,
    '',
    `export const DOCS_DEV_RECORDS_JSON = \`${templateSafe(json)}\``,
    '',
  ].join('\n')
}

if (import.meta.main) {
  const check = process.argv.includes('--check')
  const text = generate()
  if (text === null) {
    console.error(
      `[docs-corpus] commit ${DOCS_SOURCE_COMMIT} is not in this clone; fetch full history to regenerate`,
    )
    process.exit(check ? 2 : 1)
  }
  if (check) {
    const current = readFileSync(OUTPUT, 'utf8')
    if (current !== text) {
      console.error(
        '[docs-corpus] committed corpus differs from a fresh generation',
      )
      process.exit(1)
    }
    console.log('[docs-corpus] committed corpus matches a fresh generation')
  } else {
    writeFileSync(OUTPUT, text)
    console.log(`[docs-corpus] wrote ${OUTPUT}`)
  }
}
