// Copyright 2026 Qianmo AgentNest Team
// SPDX-License-Identifier: AGPL-3.0-or-later

/**
 * `reasoning_details` carried from one chat turn to the next (P18.12,
 * follow-up from the P18.8 audit; design `providers-console-m1.md` §5.4
 * 「读」「回放」, §5.6 row 7).
 *
 * P18.8 reads `reasoning_details` for its text (`reasoningStream.ts`) and
 * drops the array. OpenRouter wants it back verbatim on the next request of a
 * tool loop — "the entire sequence of consecutive reasoning blocks must match
 * the outputs generated by the model during the original request"
 * (https://openrouter.ai/docs/use-cases/reasoning-tokens, fetched
 * 2026-10-03T18:57Z).
 *
 * The path, end to end:
 *   1. capture — the chat lane taps the raw SDK chunks (before
 *      `normalizeReasoningChunks` rewrites them) and puts the concatenated
 *      array on the assistant message under
 *      {@link OPENAI_REASONING_DETAILS_FIELD}, stamped with the vendor and
 *      model that produced it (`src/services/qianmo/modelCompat/
 *      reasoningDetailsReplay.ts`);
 *   2. conversion — `anthropicMessagesToOpenAI` copies the stamped value onto
 *      the converted assistant message under {@link CARRIED_REASONING_DETAILS},
 *      a symbol key no serialiser writes;
 *   3. send — the chat lane's send boundary writes it as `reasoning_details`
 *      only for the vendor and model that produced it.
 *
 * A symbol for the same reason as `geminiToolSignature.ts`: the conversion
 * does not know the target, and a plain key would reach strict endpoints.
 */

/**
 * Field on an AssistantMessage's `message` object; message-level, like
 * `_openaiReasoningItems`.
 */
export const OPENAI_REASONING_DETAILS_FIELD = '_openaiReasoningDetails'

/**
 * Registered (`Symbol.for`) so the send boundary in `src/` can read it
 * without this package exporting it; the key string is the contract.
 */
export const CARRIED_REASONING_DETAILS: unique symbol = Symbol.for(
  'qianmo.openaiReasoningDetails',
)

/**
 * The stamped value an assistant message carries, keyed for the converted
 * message; `{}` when it carries none.
 */
export function carriedReasoningDetails(message: object): {
  [CARRIED_REASONING_DETAILS]?: object
} {
  const value = (message as Record<string, unknown>)[
    OPENAI_REASONING_DETAILS_FIELD
  ]
  return typeof value === 'object' && value !== null
    ? { [CARRIED_REASONING_DETAILS]: value }
    : {}
}
