// Copyright 2026 Qianmo AgentNest Team
// SPDX-License-Identifier: AGPL-3.0-or-later

/**
 * `reasoning_details` captured on the chat lane and sent back verbatim, to
 * OpenRouter and MiniMax only (P18.12, follow-up from the P18.8 audit; design
 * `providers-console-m1.md` §5.4 「回放」, §5.6 row 7). The package side of
 * the path is `packages/@ant/model-provider/src/shared/qianmo/
 * reasoningDetails.ts`.
 *
 * Capture: the raw SDK chunks are tapped before the stream adapter normalises
 * them (the adapter turns `reasoning_details` into `reasoning_content` and
 * keeps nothing else). OpenRouter's streaming contract: "The complete
 * reasoning sequence is built by concatenating all chunks in order"
 * (https://openrouter.ai/docs/use-cases/reasoning-tokens, fetched
 * 2026-10-03T18:57Z) — so each chunk's array is appended as it arrives, and
 * the sink is emptied when a retry starts a new attempt.
 *
 * 规则来源 NousResearch/hermes-agent（MIT，Copyright (c) 2025 Nous Research，
 * 声明见 NOTICE 五），取于 `f9b29c49b6`（2026-10-03 取用）：
 * `agent/chat_completion_helpers.py:2249-2269` — the array is passed back
 * "unmodified so providers … can maintain reasoning continuity across turns",
 * because entries carry opaque fields (signature, encrypted_content) that
 * must be preserved exactly. Only the rule is taken; the code is ours.
 *
 * Qianmo differences, on purpose:
 *   - only OpenRouter and MiniMax hosts get it (design §5.4); hermes keeps it
 *     on the message for every target;
 *   - the value is stamped with the vendor and the wire model that produced
 *     it and replayed only to that vendor and that model. OpenRouter requires
 *     the sequence to "match the outputs generated by the model during the
 *     original request", which another model's blocks cannot;
 *   - captured only when the request went to one of those hosts, so no other
 *     session's transcript grows the field.
 * MiniMax's OpenAI-compatible reference page
 * (https://platform.minimax.io/docs/api-reference/text-openai-api, fetched
 * 2026-10-03T18:55Z) documents `reasoning_split` → `reasoning_content` and
 * does not mention `reasoning_details`; the MiniMax row is the design's and
 * only takes effect if a MiniMax stream carries the array.
 */
import type { ChatCompletionChunk } from 'openai/resources/chat/completions/completions.mjs'
import type { ChatCompletionMessageParam } from 'openai/resources/chat/completions/completions.mjs'
import { targetHostIs } from './targetMatch.js'

/** Same as `OPENAI_REASONING_DETAILS_FIELD` in the package (not exported). */
const OPENAI_REASONING_DETAILS_FIELD = '_openaiReasoningDetails'

/** Same registered symbol as `CARRIED_REASONING_DETAILS` in the package. */
const CARRIED_REASONING_DETAILS: unique symbol = Symbol.for(
  'qianmo.openaiReasoningDetails',
)

type ReplayVendor = 'openrouter' | 'minimax'

const REPLAY_VENDORS: readonly { vendor: ReplayVendor; hosts: string[] }[] = [
  { vendor: 'openrouter', hosts: ['openrouter.ai'] },
  { vendor: 'minimax', hosts: ['minimax.io', 'minimaxi.com', 'minimax.cn'] },
]

/** The stamped value kept on the assistant message. */
type StampedReasoningDetails = {
  vendor: ReplayVendor
  model: string
  details: unknown[]
}

type Target = { model: string; baseURL: string | undefined }

/** The vendor that takes `reasoning_details` back, if `baseURL` is one. */
export function reasoningDetailsVendor(
  baseURL: string | undefined,
): ReplayVendor | undefined {
  return REPLAY_VENDORS.find(row => targetHostIs(baseURL, row.hosts))?.vendor
}

/**
 * Pass `stream` through unchanged, appending every chunk's
 * `choices[0].delta.reasoning_details` to `sink` in order. Empties `sink`
 * first: one call is one attempt.
 */
export async function* tapReasoningDetails(
  stream: AsyncIterable<ChatCompletionChunk>,
  sink: unknown[],
): AsyncGenerator<ChatCompletionChunk> {
  sink.length = 0
  for await (const chunk of stream) {
    const delta = chunk.choices?.[0]?.delta as
      | { reasoning_details?: unknown }
      | undefined
    if (Array.isArray(delta?.reasoning_details)) {
      sink.push(...delta.reasoning_details)
    }
    yield chunk
  }
}

/**
 * The message-level field for this turn's captured array, or `undefined`
 * when there is nothing to carry or the request did not go to a replay
 * vendor.
 */
export function reasoningDetailsMetadata(
  details: readonly unknown[],
  target: Target,
): Record<string, unknown> | undefined {
  const vendor = reasoningDetailsVendor(target.baseURL)
  if (!vendor || details.length === 0) return undefined
  const stamped: StampedReasoningDetails = {
    vendor,
    model: target.model,
    details: [...details],
  }
  return { [OPENAI_REASONING_DETAILS_FIELD]: stamped }
}

function isStamped(value: unknown): value is StampedReasoningDetails {
  if (typeof value !== 'object' || value === null) return false
  const record = value as Record<string, unknown>
  return (
    typeof record.vendor === 'string' &&
    typeof record.model === 'string' &&
    Array.isArray(record.details) &&
    record.details.length > 0
  )
}

type AssistantParam = Extract<ChatCompletionMessageParam, { role: 'assistant' }>
type Carrying = AssistantParam & {
  [CARRIED_REASONING_DETAILS]?: unknown
  reasoning_details?: unknown
}

/**
 * `message` with its carried array written as `reasoning_details` when the
 * target is the vendor and model that produced it; the same object
 * otherwise.
 */
export function replayReasoningDetails<T extends AssistantParam>(
  message: T,
  target: Target,
): T {
  const carried = (message as Carrying)[CARRIED_REASONING_DETAILS]
  if (!isStamped(carried)) return message
  if ((message as Carrying).reasoning_details !== undefined) return message
  if (
    carried.vendor !== reasoningDetailsVendor(target.baseURL) ||
    carried.model !== target.model
  ) {
    return message
  }
  return { ...message, reasoning_details: carried.details }
}
